const data = [
  {
    id: "1",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "13",
    month: "June",
    venue: "Admin Block",
    register_link: "https://forms.gle/eSBNFrSf1YTZ8Krx6",
    room: "416",
    cardColor: "red",
  },
  {
    id: "2",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "13",
    month: "June",
    venue: "Admin Block",
    register_link: "https://forms.gle/eSBNFrSf1YTZ8Krx6",
    room: "416",
    cardColor: "green",
  },
  {
    id: "3",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "12",
    month: "June",
    venue: "Admin Block",
    register_link: "https://forms.gle/eSBNFrSf1YTZ8Krx6",
    room: "416",
    cardColor: "blue",
  },
  {
    id: "4",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "14",
    month: "June",
    venue: "Admin Block",
    register_link: "https://www.youtube.com/",
    room: "416",
    cardColor: "orange",
  },
  {
    id: "5",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "15",
    month: "June",
    venue: "Admin Block",
    register_link: "https://www.linkedin.com/in/harsha-gandeti/",
    room: "416",
    cardColor: "purple-dark",
  },
  {
    id: "6",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "16",
    month: "June",
    venue: "Admin Block",
    register_link: "https://github.com/harshagandeti",
    room: "416",
    cardColor: "maroon",
  },
  {
    id: "7",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "13",
    month: "June",
    venue: "Admin Block",
    room: "416",
    register_link: "https://forms.gle/eSBNFrSf1YTZ8Krx6",
    cardColor: "orange",
  },
  {
    id: "8",
    name: "Don't Judge Each Day By The Harvest You Reap But By The Seeds That You Plant.",
    time: "10:30 AM",
    date: "13",
    month: "June",
    venue: "Admin Block",
    room: "416",
    register_link: "https://forms.gle/DRqYcMzHjhBFuQCV7",
    cardColor: "blue-dark",
  },
];

export default data;
